# -*- coding: utf-8 -*-
"""Smart Credit Decision System using Predictive Analytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mf9WRSBZoZr8fOKruyHcJE9Us4V-UJDj

# Project Title

<div style="text-align: center; padding: 40px 20px;
            background: linear-gradient(135deg, #667eea, #764ba2);
            color: white; border-radius: 12px; margin-bottom: 25px;">

  <h1 style="font-weight: 600; font-size: 28px; margin-bottom: 10px;">
    Smart Credit Decision System using Predictive Analytics
  </h1>

  <p style="font-size: 16px; opacity: 0.9; font-style: italic;">
    Driving smarter financial decisions through predictive intelligence and risk modeling
  </p>

</div>

<div style="text-align: center; padding: 20px;">
    
  <img src="https://raw.githubusercontent.com/sudhakaran-G/main-project/73a086c6537a9067ba7f63b26434fafcd022c376/credit-risk-dashboard-banner.jpeg"
       style="width: 100%; max-width: 850px; border-radius: 12px;
              box-shadow: 0px 8px 25px rgba(0,0,0,0.2);">
    <p style="font-size: 14px; opacity: 0.8;">
  A Machine Learning Approach to Credit Risk Assessment
</p>

</div>

# Domain
  
<div style="text-align: center; padding: 25px;
            background: linear-gradient(135deg, #667eea, #764ba2);
            color: white;
            border-radius: 12px;
            margin: 20px 0;">

  

  <p style="font-size: 16px; font-weight: 500;">
    Financial Risk Analytics | Credit Risk Modeling & Approval Decision Systems using Machine Learning
  </p>

  

</div>

# Objective

1. To perform exploratory data analysis (EDA) in order to uncover key patterns, trends, and hidden relationships influencing customer credit behavior

2. To clean, transform, and preprocess raw financial data to ensure high data quality and analytical reliability

3. To engineer meaningful features and build predictive models for identifying high-risk and low-risk customers

4. To develop clear and impactful visualizations that effectively communicate customer risk profiles and financial insights

5. To generate actionable insights and data-driven recommendations that support credit approval decision-making and risk mitigation

# Outcome

<p style="text-align: center; font-size: 15px; font-style: italic;
            color: #555; margin-bottom: 20px;">
    <strong>
    Enabled data-driven credit decision-making by transforming raw customer data into a predictive risk assessment system.
    </strong>
  </p>

1. Successfully identified key factors influencing customer creditworthiness, such as income level, employment status, and payment history

2. Developed a structured and clean dataset through effective data preprocessing and feature engineering, improving model performance and reliability

3. Built a predictive model capable of classifying customers into high-risk and low-risk segments with measurable accuracy

4. Generated clear visual insights that highlight customer behavior patterns and risk distribution

5. Created a risk-based classification system that supports informed credit approval decisions

6. Delivered actionable recommendations to minimize financial risk and reduce the likelihood of default

# Dataset Information

<!-- Source Details -->
  <p style="font-size: 14px; color: #444; line-height: 1.8;">
    <strong>Source:</strong>
    <a href="https://www.kaggle.com/datasets/saidsalahibrahim/a-credit-card-dataset-for-machine-exam?select=application_record.csv" target="_blank">
      Kaggle – Credit Card Dataset
    </a><br>

**Name**: Credit Card Approval Prediction

**Original Uploader**: rikdifos (Kaggle user)

**Created**: November 2019

**Timeline**: Created in 2019 and widely used for machine learning projects from 2020 onwards

<!-- Description -->
  <h3 style="color: #555; margin-top: 20px;">📊 Description</h3>
  <p style="font-size: 14px; color: #444; line-height: 1.7;">
    The dataset contains customer demographic, financial, and credit history information used to analyze credit behavior
    and build predictive models for identifying high-risk and low-risk applicants. It consists of two datasets
    (application and credit records) that are merged using a unique customer ID to support credit risk analysis and decision-making.
  </p>
<!-- Purpose -->
  <h3 style="color: #555; margin-top: 20px;">🎯 Purpose</h3>
  <p style="font-size: 14px; color: #444;">
    To predict whether a customer is:
  </p>
  <ul style="font-size: 14px; color: #444; line-height: 1.6;">
    <li>✅ Good Client</li>
    <li>❌ Bad Client</li>
  </ul>

  <!-- Structure -->
  <h3 style="color: #555; margin-top: 20px;">🧩 Dataset Structure</h3>

  <p style="font-size: 14px; color: #444;">
    <strong>1. Application Data (application_record.csv)</strong>
  </p>
  <ul style="font-size: 14px; color: #444; line-height: 1.6;">
    Customer personal and financial details,
    <li>Gender, Income, Education</li>
    <li>Family status, Housing</li>
    <li>Employment details</li>
    <li>Number of children</li>
  </ul>

  <p style="font-size: 14px; color: #444;">
    <strong>2. Credit History Data (credit_record.csv)</strong>
  </p>
  <ul style="font-size: 14px; color: #444; line-height: 1.6;">
    <li>Monthly records</li>
    <li>Loan status (delay / paid / default)</li>
  </ul>

  Key Business Context

 In the banking and financial services industry, credit card approval is a critical component of risk management and decision-making.


   *  **Credit scoring (Risk control system)**: Financial institutions utilize credit scoring systems to evaluate the creditworthiness of applicants and control potential risk exposure

   *  **Customer data analysis (Default probability prediction)**: Historical and demographic customer data is analyzed to estimate the probability of default and understand financial behavior patterns

   *  **Decision-Making Process (Approve / Reject)**: Based on risk assessment, applicants are classified to support approval or rejection decisions, ensuring optimal balance between risk and profitability

   * **Modeling Techniques:** Advanced models such as Random Forest and Gradient Boosting are used to improve predictive performance and capture complex patterns


The project leverages statistical and machine learning models to support data-driven credit risk assessment and approval decisions in the banking domain.

# Type of Analysis

  <div style="padding: 30px; background: #f8f9fc;
            border-radius: 12px; margin: 25px 0;
            box-shadow: 0px 6px 18px rgba(0,0,0,0.08);">
  <p style="text-align: center; font-size: 14px; color: #555;
            margin-bottom: 25px; line-height: 1.7;">
    <strong>
      The project integrates descriptive, diagnostic, predictive, and prescriptive analytics
      to enable end-to-end credit risk decision-making.
    </strong>
  </p>

  <!-- Descriptive -->
  <div style="margin-bottom: 15px;">
    <h3 style="color: #667eea;">📌 Descriptive Analysis</h3>
    <p style="font-size: 14px; color: #444; line-height: 1.7;">
      Summarizes and explores the dataset by analyzing key variables such as customer demographics,
      income distribution, and credit behavior patterns.
    </p>
  </div>

  <!-- Diagnostic -->
  <div style="margin-bottom: 15px;">
    <h3 style="color: #667eea;">🔍 Diagnostic Analysis</h3>
    <p style="font-size: 14px; color: #444; line-height: 1.7;">
      Identifies underlying causes behind observed patterns, including factors contributing to
      high-risk customers and default behavior.
    </p>
  </div>

  <!-- Predictive -->
  <div style="margin-bottom: 15px;">
    <h3 style="color: #667eea;">🤖 Predictive Analysis</h3>
    <p style="font-size: 14px; color: #444; line-height: 1.7;">
      Builds machine learning models to forecast customer credit risk and classify applicants
      into high-risk and low-risk segments.
    </p>
  </div>

  <!-- Prescriptive -->
  <div>
    <h3 style="color: #667eea;">💡 Prescriptive Analysis</h3>
    <p style="font-size: 14px; color: #444; line-height: 1.7;">
      Provides data-driven recommendations to support credit approval decisions and
      minimize financial risk.
    </p>
  </div>

</div>

<div style="margin-top: 20px; padding: 15px;
            background: #eef2ff; border-left: 5px solid #667eea;
            border-radius: 8px;">

  <p style="font-size: 14px; color: #333; margin: 0;">
    <strong>
      This multi-layered analytical approach ensures a comprehensive understanding
      of customer risk and enables data-driven credit decision-making.
    </strong>
  </p>

</div>

<div style="text-align: center; margin: 30px 0;">

  <h2 style="color: #333; margin-bottom: 15px;">
    🔄 Project Workflow
  </h2>

  <img src="https://raw.githubusercontent.com/sudhakaran-G/main-project/main/credit-risk-workflow.png"
       alt="Credit Risk Workflow Diagram"
       style="width: 100%; max-width: 900px;
              border-radius: 12px;
              box-shadow: 0px 8px 25px rgba(0,0,0,0.15);">

</div>

# Stages for DA Project

## Stage 1 – Problem Definition and Dataset Selection

Define the business problem and expected outcome

Choose dataset and explain its source, size, and features

Import libraries, load dataset

Dataset description (rows, columns, features)

Initial EDA (head, info, describe, shape, null checks, duplicate check)
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

app_record= pd.read_csv('/content/drive/MyDrive/ENTRI/Main project/application_record.csv')
credit_record= pd.read_csv('/content/drive/MyDrive/ENTRI/Main project/credit_record.csv')

app_record

credit_record

print(f" First 10 Rows of the Application Record : ")

app_record.head(10)

print(f" First 10 Rows of the Credit Record : ")

credit_record.head(10)

print(f" Last 5 Rows of the app_record : ")

app_record.tail()

print(f" Last 5 Rows of the credit_record : ")

credit_record.tail()

print(f" General Information of app_record : " )

app_record.info()

print(f" General Information of credit_record : " )

credit_record.info()

print (f" Checking Null values : ")

app_record.isnull().sum()

print (f" Checking Null values : ")

credit_record.isnull().sum()

print(f" Number of Unique Values : ")

app_record.nunique()

print(f" Number of Unique Values : ")

credit_record.nunique()

print(f" Statistical Summary of the Dataset : ")

print()

app_record.describe()

print(f" Statistical Summary of the Dataset : ")

print()

credit_record.describe()

print(f" Size of the Elements : {app_record.size} " )

print(f" Size of the Elements : {credit_record.size} " )

print(f" Application Record:  {app_record.shape[0]} Rows , {app_record.shape[1]} Coulmns" )

print(f" Credit Record:  {credit_record.shape[0]} Rows , {credit_record.shape[1]} Coulmns" )

print(f" Datatypes of the DataFrame : ")

app_record.dtypes

print(f" Datatypes of the DataFrame : ")

credit_record.dtypes

print("Columns List :\n")
print(*app_record.columns, sep='\n')

print("Columns List :\n")
print(*credit_record.columns, sep='\n\n')

# Finding Duplicate Values
print(f" Duplicate Values : {app_record.duplicated().sum()} " )

# Finding Duplicate Values
print(f" Duplicate Values : {credit_record.duplicated().sum()} " )

app_record.count()

credit_record.count()

print(f""" Values of the DataFrame :

{app_record.values} """)

print(f""" Values of the DataFrame :

{credit_record.values} """)

print(f"🔗 Common IDs: {len(set(app_record['ID']).intersection(set(credit_record['ID']))):,}")

"""## Stage 2 – Data Cleaning and Pre-processing

Handle missing values (impute or drop)

Handle duplicates

Treat outliers if required

Check skewness and apply transformations

Convert data types if needed

Feature transformations (date parts, derived fields if required for analysis)

<div style="padding: 30px; background: #f8f9fc;
            border-radius: 12px; margin: 25px 0;
            box-shadow: 0px 6px 18px rgba(0,0,0,0.08);">

  <h2 style="text-align: center; color: #333; margin-bottom: 20px;">
    🧹 Stage 2 – Data Cleaning & Pre-processing
  </h2>

  <p style="text-align: center; font-size: 14px; color: #555;
            margin-bottom: 25px; line-height: 1.7;">
    <strong>
      This stage focuses on preparing raw data for analysis by improving data quality,
      handling inconsistencies, and transforming features for effective modeling.
    </strong>
  </p>

  <ul style="font-size: 14px; color: #444; line-height: 1.8;">

  <li>
      <strong>Missing Value Handling:</strong> Identified and treated missing values using appropriate techniques such as imputation or removal
    </li>

  <li>
      <strong>Duplicate Removal:</strong> Detected and removed duplicate records to ensure data consistency and accuracy
    </li>

  <li>
      <strong>Outlier Treatment:</strong> Analyzed and handled outliers where necessary to prevent distortion in model performance
    </li>

   <li>
      <strong>Skewness Correction:</strong> Evaluated feature distributions and applied transformations (e.g., log/normalization) to reduce skewness
    </li>

  <li>
      <strong>Data Type Conversion:</strong> Converted variables into appropriate data types to ensure compatibility with analytical and modeling techniques
   </li>

   <li>
      <strong>Feature Engineering:</strong> Created derived features such as date-based attributes and aggregated variables to enhance predictive capability
    </li>

  </ul>

</div>
"""

#Add Target column

credit_record['target'] = credit_record['STATUS'].apply(
    lambda x: 1 if x in ['2','3','4','5'] else 0
)
credit_record

# Group by ID
credit_group = credit_record.groupby('ID')['target'].max().reset_index()

credit_group.head()

# Merge: application record + credit target based on ID

customer_credit_risk_profile = app_record.merge(
    credit_group,
    on='ID',
    how='inner'
)
customer_credit_risk_profile

# Replace target values
customer_credit_risk_profile['target'] = customer_credit_risk_profile['target'].replace({
    0: 'Good',
    1: 'Risk'
})
customer_credit_risk_profile['target']

customer_credit_risk_profile = customer_credit_risk_profile.fillna('Unknown')
customer_credit_risk_profile

customer_credit_risk_profile['DAYS_EMPLOYED'] = (
    customer_credit_risk_profile['DAYS_EMPLOYED']
    .apply(
        lambda x: 'No Employment Record'
        if pd.notnull(x) and x > 0
        else abs(x) if pd.notnull(x)
        else x
    )
)

customer_credit_risk_profile['DAYS_EMPLOYED']

# Numeric conversion
customer_credit_risk_profile['DAYS_EMPLOYED'] = pd.to_numeric(
    customer_credit_risk_profile['DAYS_EMPLOYED'],
    errors='coerce'
)

customer_credit_risk_profile['DAYS_EMPLOYED']

# Today's date
today = pd.to_datetime('today')
today

# Date of Birth calculate
customer_credit_risk_profile['D.O.B'] = (
    today + pd.to_timedelta(
        customer_credit_risk_profile['DAYS_BIRTH'],
        unit='D'
    )
)
customer_credit_risk_profile['D.O.B']

customer_credit_risk_profile['Date_of_Joining'] = (
   today - pd.to_timedelta(
        customer_credit_risk_profile['DAYS_EMPLOYED'],
        unit='D'
    )
)
customer_credit_risk_profile['Date_of_Joining']

# Only date format
customer_credit_risk_profile['D.O.B'] = (
    customer_credit_risk_profile['D.O.B'].dt.date)
customer_credit_risk_profile['D.O.B']

customer_credit_risk_profile['Date_of_Joining'] = (
    customer_credit_risk_profile['Date_of_Joining'].dt.date
)

customer_credit_risk_profile['Date_of_Joining']

# Age calculate
customer_credit_risk_profile['Age'] = (
    customer_credit_risk_profile['DAYS_BIRTH'] // 365.25).abs()
customer_credit_risk_profile['Age']

# Experience
customer_credit_risk_profile['Experience_Years'] = (
    customer_credit_risk_profile['DAYS_EMPLOYED'] // 365
)

customer_credit_risk_profile['Experience_Years']

# Column order change
customer_credit_risk_profile = customer_credit_risk_profile[
    [
        'ID',
        'CODE_GENDER',
        'DAYS_BIRTH',
        'D.O.B',
        'Age',
        'NAME_FAMILY_STATUS',
        'CNT_CHILDREN',
        'CNT_FAM_MEMBERS',
        'AMT_INCOME_TOTAL',
        'NAME_INCOME_TYPE',
        'NAME_EDUCATION_TYPE',
        'OCCUPATION_TYPE',
        'FLAG_OWN_CAR',
        'FLAG_OWN_REALTY',
        'NAME_HOUSING_TYPE',
        'DAYS_EMPLOYED',
        'Date_of_Joining',
        'Experience_Years',
        'FLAG_MOBIL',
        'FLAG_WORK_PHONE',
        'FLAG_PHONE',
        'FLAG_EMAIL',
        'target'
    ]
]


customer_credit_risk_profile.sample()

customer_credit_risk_profile.to_excel(
    'customer_credit_risk_profile.xlsx',
    index=False
)

"""<div style="margin-top: 20px; padding: 15px;
            background: #eef2ff; border-left: 5px solid #667eea;
            border-radius: 8px;">

  <p style="font-size: 14px; color: #333; margin: 0;">
    <strong>
      Effective data preprocessing significantly improved data quality and laid the foundation
      for accurate and reliable predictive modeling.
    </strong>
  </p>

</div>

## Stage 3 – EDA and Visualizations

Univariate Analysis → distribution of single variables (countplot, histogram, boxplot)

Bivariate Analysis → relation between two variables (scatterplot, barplot, correlation heatmap)

Multivariate Analysis → relation among 3+ variables (pairplot, grouped analysis, pivot tables, advanced plots)

Interpretation MUST with every visualization

Focus on business story not just charts

Each chart must be in seperate cells.
"""

plt.figure(figsize=(6,5))

# Color mapping
custom_palette = {
    'Good': 'green',
    'Risk': 'red'
}

ax = sns.countplot(
    x='target',
    data=customer_credit_risk_profile,
    palette=custom_palette
)

# Total count
total = len(customer_credit_risk_profile)

# Percentage labels
for p in ax.patches:

    count = p.get_height()
    percentage = 100 * count / total

    ax.annotate(
        f'{percentage:.1f}%',
        (p.get_x() + p.get_width()/2., count),
        ha='center',
        va='bottom',
        fontsize=10
    )

plt.title("Good vs Risk Customers")
plt.xlabel("Customer Status")
plt.ylabel("Count")

plt.show()

# Value counts
print(customer_credit_risk_profile['target'].value_counts())

print("""
This chart shows the distribution of customers based on their credit risk status.
The customers are categorized into:

  * Good customers
  * Risk customers

Different colors are used to clearly distinguish each category:

  * Green → Good
  * Red → Risk

The percentage labels on top of the bars represent the proportion of customers in each category.

1.  The chart indicates that the majority of customers belong to the Good category, which means most customers have healthy repayment behavior and lower default risk.
2.  A smaller percentage of customers fall under the Risk category, indicating customers with delayed payments or higher credit risk.
Features used in this visualization:

  * target

The target column was created using customer credit repayment history:

  * Good → financially stable customers
  * Risk → customers with repayment delays/default behavior
This visualization helps evaluate the overall credit quality of the customer portfolio.

Business Insights:

1.  A higher number of Good customers indicates healthier financial stability within the organization’s customer base.
2.  Risk customers can be identified for stricter monitoring and controlled loan approvals.
3.  Customers without credit history may require additional verification before financial approval decisions.

it supports,
  * Credit risk assessment
  * Customer segmentation
  * Loan approval strategy
  * Financial decision-making processes
""")

plt.figure(figsize=(6,5))

ax = sns.countplot(
    x='CODE_GENDER',
    data=customer_credit_risk_profile,
    color='blue'
)

total = len(customer_credit_risk_profile)

for p in ax.patches:

    count = p.get_height()
    percentage = 100 * count / total

    ax.annotate(
        f'{percentage:.1f}%',
        (p.get_x() + p.get_width()/2., count),
        ha='center',
        va='bottom'
    )

plt.title("Gender Distribution")
plt.xlabel("Gender")
plt.ylabel("Count")

plt.show()

print("""
This chart shows the distribution of customers based on gender in the credit risk dataset.

The chart indicates how many male and female customers are present in the dataset along with their percentage contribution.
It helps identify whether the dataset is balanced or dominated by a particular gender group.

Features used:  CODE_GENDER

Visualization used: Countplot

If one gender category has significantly higher customer count:

  * the dataset may be gender-skewed
  * business decisions and predictive models could become biased toward that group

This insight is important for:

  * customer segmentation
  * fairness analysis
  * balanced credit risk assessment
  * targeted financial product strategies

Business Insight:

Understanding gender distribution helps financial institutions analyze customer demographics and ensure balanced risk evaluation across different customer groups.

""")

plt.figure(figsize=(10,5))

sns.histplot(
    customer_credit_risk_profile['AMT_INCOME_TOTAL'],
    bins=30,
    kde=True
)

plt.title("Income Distribution")
plt.xlabel("Income")
plt.ylabel("Frequency")

plt.show()

print("""
1.  This histogram visualizes the distribution of customer annual income in the dataset.
2.  The KDE (Kernel Density Estimation) curve helps understand the overall income density and pattern more smoothly.
3.  The chart shows that most customers fall within the low-to-middle income range, while only a smaller number of customers belong to higher income groups.
4.  It also highlights the presence of income outliers with significantly higher earnings.

Features used:  AMT_INCOME_TOTAL

Visualization used: Histogram & KDE Curve

The organization mainly serves middle-income customers, which may influence:

  * loan approval policies
  * credit limit allocation
  * risk management strategies
  * targeted financial products

The presence of high-income outliers may indicate premium customer segments with potentially lower repayment risk.

Business Insight:

Income distribution is a critical factor in credit risk analysis because customer repayment capacity is directly linked to earning potential.

Understanding income patterns helps financial institutions:

  * identify financially stable applicants
  * design customized loan products
  * improve risk-based customer segmentation
  * optimize credit approval decisions


""")

plt.figure(figsize=(10,5))

sns.histplot(
    customer_credit_risk_profile['Age'],
    bins=25,
    kde=True,
    color='orange'
)

plt.title("Age Distribution")
plt.xlabel("Age")
plt.ylabel("Frequency")

plt.show()


print("""
1.  This histogram shows the distribution of customer ages in the credit risk dataset.
2.  The KDE (Kernel Density Estimation) curve provides a smoother view of the age distribution pattern.
3.  The chart indicates that most customers belong to the working-age population, while fewer customers are present in very young or older age groups.
4.  It helps identify the dominant customer age segment in the organization.

Features used:  Age

Visualization used: Histogram & KDE Curve

The chart suggests that the company mainly deals with economically active individuals who are more likely to:

  * have stable income
  * maintain repayment capability
  * actively use financial products

Age distribution also helps identify:

  * potential high-risk age groups
  * target customer segments
  * long-term customer acquisition opportunities

Business Insight

Age is an important factor in credit risk analysis because repayment behavior, income stability, and financial responsibility often vary across age groups.

Understanding customer age patterns helps financial institutions:
  * improve customer segmentation
  * personalize loan offerings
  * optimize marketing strategies
  * strengthen risk assessment models



""")

plt.figure(figsize=(12, 6))

# Value counts
income_counts = (
    customer_credit_risk_profile['NAME_INCOME_TYPE']
    .value_counts()
)

# Total count
total = income_counts.sum()

# Horizontal bar chart
bars = plt.barh(
    income_counts.index,
    income_counts.values,
    color='blue'
)

# Percentage labels
for bar in bars:

    count = bar.get_width()
    percentage = (count / total) * 100

    plt.text(
        count + 50,
        bar.get_y() + bar.get_height()/2,
        f'{percentage:.1f}%',
        va='center',
        fontsize=10
    )

plt.xlabel('Count', fontsize=12)
plt.ylabel('Income Type', fontsize=12)

plt.title(
    'Income Type Distribution',
    fontsize=14,
    fontweight='bold'
)

plt.grid(alpha=0.3, axis='x')

plt.tight_layout()

plt.show()

print("""
1.  This chart shows the distribution of different customer income types in the dataset using a horizontal bar chart.
2.  It helps visualize which income category has the highest number of customers.
3.  The chart indicates that most customers belong to a specific income category such as Working professionals or Commercial associates, while smaller groups belong to Pensioners, Students, or State servants.
4.  The percentage labels clearly show the contribution of each income group to the overall customer population.

Features used:

NAME_INCOME_TYPE

Visualization techniques used:

Horizontal Bar Chart (plt.barh)
Percentage Annotation
Count Distribution Analysis
""")

plt.figure(figsize=(7,5))

custom_palette = {
    'Good': 'green',
    'Risk': 'red'
}

ax = sns.countplot(
    x='CODE_GENDER',
    hue='target',
    data=customer_credit_risk_profile,
    palette=custom_palette
)

total = len(customer_credit_risk_profile)
for p in ax.patches:

    count = p.get_height()
    percentage = 100 * count / total

    ax.annotate(
        f'{percentage:.1f}%',
        (p.get_x() + p.get_width()/2., count),
        ha='center',
        va='bottom',
        fontsize=10
    )

plt.title("GENDER vs Risk")
plt.xlabel("Gender")
plt.ylabel("Count")

plt.legend(title='Customer Status')

plt.show()

print("""

1.  This chart compares customer gender with their credit risk status using different color categories.
2.  The visualization helps analyze how risk distribution varies between male and female customers.
3.  The chart shows the number and percentage of,
  * Good customers
  * Risk customers
within each gender category.
4.  It helps identify whether a particular gender group has higher representation in the risk category.

Features used:  CODE_GENDER & target

Visualization used: Countplot & Hue-based categorical comparison

Color representation:
  * Green → Good Customers
  * Red → Risk Customers

determine:
  * whether risk is evenly distributed across genders
  * whether one gender group contributes more to risky customers
  * demographic trends in repayment behavior

supports:
  * customer segmentation
  * fair lending analysis
  * demographic-based financial planning
  * risk monitoring strategies

Business Insight:

 Gender-based analysis helps financial institutions evaluate customer behavior patterns and identify demographic trends in credit performance.

It support,
  * balanced credit evaluation
  * targeted customer engagement
  * improved portfolio management
  * bias monitoring in lending decisions
""")

plt.figure(figsize=(7,5))

custom_palette = {
    'Good': 'green',
    'Risk': 'red'
}

ax = sns.countplot(
    x='FLAG_OWN_CAR',
    hue='target',
    data=customer_credit_risk_profile,
    palette=custom_palette
)

total = len(customer_credit_risk_profile)

for p in ax.patches:

    count = p.get_height()
    percentage = 100 * count / total

    ax.annotate(
        f'{percentage:.1f}%',
        (p.get_x() + p.get_width()/2., count),
        ha='center',
        va='bottom',
        fontsize=10
    )

plt.title("Car Ownership vs Risk")
plt.xlabel("Own Car")
plt.ylabel("Count")

plt.legend(title='Customer Status')

plt.show()

print("""

1.  This chart compares customer car ownership status with their credit risk category.
2.  It visualizes how customers who own a car and those who do not own a car are distributed across different risk levels.

The chart shows the number and percentage of:
  * Good customers
  * Risk customers
  * Customers with No Credit Record
based on car ownership status.

3.It helps identify whether owning a car is associated with lower or higher credit risk behavior.

Features used:  FLAG_OWN_CAR  & target

Visualization used: Countplot & Hue-based categorical comparison

Color representation:
  * Green → Good Customers
  * Red → Risk Customers

indicate:
  * stronger financial capacity
  * stable lifestyle
  * higher purchasing power
The chart helps identify whether customers with assets tend to show better repayment behavior compared to non-owners.

supports:
  * customer profiling
  * financial stability analysis
  * asset-based risk assessment
  * loan approval strategies

Business Insight:
 Asset ownership is often considered an important indicator in credit risk analysis.
Customers owning valuable assets such as cars may have:
 * better repayment capability
 * higher financial responsibility
 * lower default probability

These insights help financial institutions improve:
 * risk segmentation
 * loan eligibility evaluation
 * credit scoring strategies
 * customer portfolio management
""")

plt.figure(figsize=(7,5))

custom_palette = {
    'Good': 'green',
    'Risk': 'red'
}

ax = sns.countplot(
    x='FLAG_OWN_REALTY',
    hue='target',
    data=customer_credit_risk_profile,
    palette=custom_palette
)

total = len(customer_credit_risk_profile)

for p in ax.patches:

    count = p.get_height()
    percentage = 100 * count / total

    ax.annotate(
        f'{percentage:.1f}%',
        (p.get_x() + p.get_width()/2., count),
        ha='center',
        va='bottom',
        fontsize=10
    )

plt.title("OWN_REALTY vs Risk")
plt.xlabel("Own Realty")
plt.ylabel("Count")

plt.legend(title='Customer Status')

plt.show()

print("""
1.  This chart compares customer property ownership status with their credit risk category.
2.  It visualizes how customers who own real estate/property and those who do not own property are distributed across Good and Risk categories.
3.  The chart shows the number and percentage of:
  * Good customers
  * Risk customers
based on property ownership status.
4.It helps identify whether owning property is associated with better financial stability and lower credit risk.

Features used:  FLAG_OWN_REALTY & target

Visualization used: Countplot & Hue-based categorical comparison

Color representation:

  * Green → Good Customers
  * Red → Risk Customers
5.  This analysis helps evaluate the relationship between property ownership and customer repayment behavior.

Customers owning real estate may indicate:
  * stronger financial background
  * higher long-term stability
  * greater asset value
  * lower financial uncertainty
The chart helps determine whether property owners are less likely to fall into the Risk category.

supports:
  * credit eligibility assessment
  * asset-based customer profiling
  * financial stability evaluation
  * risk segmentation strategies

Business Insight:

Property ownership is considered an important indicator in credit risk analysis because it often reflects long-term financial security.

Customers with real estate assets may:
  * have stronger repayment capability
  * maintain better financial discipline
  * show lower default probability

These insights help financial institutions improve:
  * loan approval decisions
  * credit scoring models
  * premium customer targeting
  * portfolio risk management

""")

plt.figure(figsize=(10,6))

sns.scatterplot(
    x='Age',
    y='AMT_INCOME_TOTAL',
    hue='target',
    data=customer_credit_risk_profile,
    palette=custom_palette
)

plt.title("Age vs Income")
plt.xlabel("Age")
plt.ylabel("Income")

plt.show()

print("""
1.  This scatter plot visualizes the relationship between customer age and annual income along with their credit risk category.
2.  Each point in the chart represents an individual customer.
3.  The chart shows how customer income varies across different age groups and risk categories.

It helps identify:
  * whether higher income customers belong to specific age groups
  * whether risky customers are concentrated in certain income or age ranges
  * patterns between earning capacity and credit behavior

  Features used:  Age,  AMT_INCOME_TOTAL  & target

Visualization used: Scatter Plot

Color representation:

  * Green → Good Customers
  * Red → Risk Customers
4.  This analysis helps understand how age and income together influence customer credit risk behavior.

The chart can reveal:
  * financially stable customer segments
  * high-income low-risk customers
  * younger or lower-income customers with higher risk exposure
  * customer clusters based on earning potential

supports:
  * customer segmentation
  * income-based credit analysis
  * targeted loan offerings
  * personalized financial products

Business Insight:

Age and income are two critical indicators in credit risk analysis because repayment capability often depends on both earning stability and career stage.

Financial institutions can use this analysis to:
  * identify low-risk premium customers
  * improve credit approval decisions
  * design age-specific financial products
  * optimize risk-based lending strategies
""")

plt.figure(figsize=(10,8))

numeric_df = customer_credit_risk_profile.select_dtypes(include='number')

sns.heatmap(
    numeric_df.corr(),
    annot=True,
    cmap='coolwarm'
)

plt.title("Correlation Heatmap")

plt.show()

print("""
1.  This correlation heatmap visualizes the relationship between numerical variables in the dataset.
2.  The chart displays correlation values between features using color intensity and numerical scores.
It shows,
  * positive correlations
  * negative correlations
  * weak or strong relationships
between numerical features.

Correlation values range from:
  * +1 → strong positive relationship
  * 0 → no relationship
  * -1 → strong negative relationship
Darker colors represent stronger relationships between variables.

Features used:
  * Age
  * AMT_INCOME_TOTAL
  * CNT_CHILDREN
  * CNT_FAM_MEMBERS
  * DAYS_BIRTH
  * DAYS_EMPLOYED
other numerical columns from the dataset

Visualization:  Correlation Heatmap

Method used:  numeric_df.corr()

3.This analysis helps identify which numerical variables are closely related to each other.

The chart helps detect:
  * highly influential variables
  * redundant features
  * patterns between financial and demographic variables

It also helps understand:
  * whether income increases with age
  * whether family size impacts income
  * whether employment duration relates to customer stability

supports:
  * feature selection
  * predictive modeling
  * risk analysis
  * business intelligence decisions

Business Insight:

Correlation analysis is important in credit risk analytics because strongly related variables can significantly influence customer repayment behavior.

Financial institutions can use these insights to:
* improve machine learning model accuracy
* remove unnecessary variables
* identify key drivers of credit risk
* enhance customer profiling strategies
* optimize data-driven decision making
""")

sns.pairplot(
    customer_credit_risk_profile[
        ['Age', 'AMT_INCOME_TOTAL', 'CNT_CHILDREN']
    ]
)

plt.show()

print("""

Explain the Chart:
This pairplot visualizes the relationship among multiple numerical variables
including customer age, annual income, and number of children.

It displays:
- scatter plots between variables
- distribution plots for each individual feature

------------------------------------------------------------

What is it saying?
The chart helps identify:
- relationships between variables
- customer distribution patterns
- clusters and trends
- possible outliers in the dataset

It shows how:
- income varies with age
- family size relates to income
- age relates to number of children

------------------------------------------------------------

What features you used?
Features used:
- Age
- AMT_INCOME_TOTAL
- CNT_CHILDREN

Visualization used:
- Pairplot
- Scatter plots
- Distribution plots

------------------------------------------------------------

From this what are you showing us?
This analysis helps understand how multiple customer characteristics
interact with each other.

The chart can reveal:
- whether older customers earn higher income
- whether customers with children belong to certain income groups
- whether family responsibilities influence earning patterns

It also helps identify:
- customer segments
- unusual customer profiles
- hidden relationships among variables

------------------------------------------------------------

Business Insight:
Multivariate analysis provides deeper understanding of customer behavior
by analyzing multiple features together instead of individually.

Financial institutions can use these insights to:
- improve customer segmentation
- enhance credit risk prediction
- identify stable customer groups
- optimize targeted financial products
- strengthen data-driven lending strategies

""")

plt.figure(figsize=(12,6))

sns.countplot(
    y='NAME_INCOME_TYPE',
    hue='target',
    data=customer_credit_risk_profile,
    palette=custom_palette
)

plt.title("Income Type vs Risk")

plt.show()

print("""
Explain the Chart:
This chart compares different customer income types with their credit risk status.

It visualizes how customers from various employment and income categories
are distributed across Good and Risk classifications.

------------------------------------------------------------

What is it saying?
The chart shows the number of Good and Risk customers
within each income category.

It helps identify:
- which income groups contain more risky customers
- which employment categories are financially stable
- how income source influences repayment behavior

------------------------------------------------------------

What features you used?
Features used:
- NAME_INCOME_TYPE
- target

Visualization used:
- Countplot
- Hue-based categorical comparison

Color representation:
- Green  → Good Customers
- Red    → Risk Customers

------------------------------------------------------------

From this what are you showing us?
This analysis helps evaluate how customer occupation and income source
affect credit risk behavior.

The chart can reveal:
- salaried employees with stable repayment behavior
- higher-risk categories among irregular income groups
- financially secure customer segments

It supports:
- customer segmentation
- income-based risk analysis
- loan eligibility evaluation
- portfolio monitoring strategies

------------------------------------------------------------

Business Insight:
Income source is a major factor in credit risk assessment because
repayment stability often depends on employment consistency.

Financial institutions can use this analysis to:
- prioritize stable income applicants
- improve risk scoring strategies
- design customized loan products
- optimize lending decisions
- reduce default exposure


""")

pivot_table = pd.pivot_table(
    customer_credit_risk_profile,
    values='AMT_INCOME_TOTAL',
    index='NAME_INCOME_TYPE',
    columns='target',
    aggfunc='mean'
)

print(pivot_table)

print("""
Explain the Chart:
This pivot table shows the average annual income of customers
across different income types and credit risk categories.

It compares how income levels vary between Good and Risk customers
within each employment category.

------------------------------------------------------------

What is it saying?
The table helps identify:
- which income groups earn higher average income
- differences between Good and Risk customers
- financial patterns across employment categories

It shows whether customers with higher income
generally belong to the Good category.

------------------------------------------------------------

What features you used?
Features used:
- NAME_INCOME_TYPE
- target
- AMT_INCOME_TOTAL

Analysis method used:
- Pivot Table
- Mean aggregation

------------------------------------------------------------

From this what are you showing us?
This analysis helps understand the relationship between
income source, earning capacity, and credit behavior.

The table can reveal:
- financially stable customer groups
- high-income low-risk segments
- employment categories with potential repayment challenges

It supports:
- customer financial profiling
- risk segmentation
- targeted lending strategies
- business decision-making

------------------------------------------------------------

Business Insight:
Average income analysis is important in credit risk management because
customers with stable and higher income are generally more capable
of maintaining regular repayments.

Financial institutions can use these insights to:
- improve credit approval policies
- identify premium customer segments
- optimize loan offerings
- reduce financial risk exposure
- strengthen customer portfolio quality

""")

print("""
1. Target Distribution Chart:

*
Interpretation:

1. Majority of customers belong to the Good category,
   indicating healthier repayment behavior.

2. Smaller portion of customers fall under Risk category,
   which suggests limited default exposure.

3. This indicates the organization currently maintains
   a relatively stable credit portfolio.

Business Insight:
The company can focus on retaining low-risk customers
while developing targeted monitoring strategies for risky applicants.
""")

"""## Stage 4 – Documentation, Insights and Presentation

Show a dashboard aligning all the charts in powerbi by connecting python in PowerBI

Summarize findings in plain English (what do the patterns mean)

Highlight 3–5 key insights (trends, anomalies, correlations)

Provide recommendations for business or decision-making

Explain the FINAL STORY WITH THE DASHBOARD

Create a PDF pasting your DASHBOARD, explaining all the above mentioned concepts and submit it

"""

# your stage 4 pdf Link

'''
step1 --> Create a docs that should have all the above mentioned
step2 --> Save it as "Stage4_doc"
Step3 --> Download it as PDF
step4 --> Upload the pdf in your drive
step5 --> Right click on your pdf in drive
step6 --> click share and change access into anyone with the link (Viewer)
step7 --> click copy link and paste it here...
You are done.
'''